nginx

diff --git a/web_server/1-install_nginx_web_server b/web_server/1-install_nginx_web_server
--- a/web_server/1-install_nginx_web_server
+++ b/web_server/1-install_nginx_web_server
@@ -1,7 +1,15 @@
 #!/usr/bin/env bash
-# script to install nginx on your web-01 server
-sudo apt-get update
-sudo apt-get -y install nginx
-sudo ufw allow 'Nginx HTTP'
-sudo echo "Nicole from Holberton School" > /var/www/html/index.nginx-debian.html
-sudo service nginx start
+# Sets up a web server with nginx, listening on port 80 and returns a custom page
+
+# Exit on error
+set -e
+
+# Update package index and install nginx
+apt-get update -y
+apt-get install -y nginx
+
+# Replace default nginx index page content
+echo 'Holberton School for the win!' > /var/www/html/index.html
+
+# Ensure Nginx is started using service command (not systemctl)
+service nginx start
